name: Apply

on:
  workflow_dispatch:

jobs:
  print-env:
    runs-on: ubuntu-latest
    env:
      CHECKPOINT_API_KEY: ${{ secrets.CHECKPOINT_API_KEY }}
      CHECKPOINT_CLOUD_MGMT_ID: ${{ secrets.CHECKPOINT_CLOUD_MGMT_ID }}
      CHECKPOINT_SERVER: ${{ secrets.CHECKPOINT_SERVER }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Print environment variables
        run: |
          echo "Environment variables:"
          env | grep CHECKPOINT_
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 'latest'
      - name: Terraform version
        run: terraform version
      - name: Terraform init inventory
        run: cd inventory; terraform init
      - name: Terraform apply inventory
        run: cd inventory; terraform apply -auto-approve
      - name: Terraform destroy inventory
        run: cd inventory; terraform destroy -auto-approve
        
