name: Apply

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  objects:
    runs-on: ubuntu-latest
    env:
      CHECKPOINT_API_KEY: ${{ secrets.CHECKPOINT_API_KEY }}
      CHECKPOINT_CLOUD_MGMT_ID: ${{ secrets.CHECKPOINT_CLOUD_MGMT_ID }}
      CHECKPOINT_SERVER: ${{ secrets.CHECKPOINT_SERVER }}
      STORAGE_ACCOUNT_NAME: ${{ secrets.STORAGE_ACCOUNT_NAME }}
      BLOB_CONTAINER_NAME: ${{ secrets.BLOB_CONTAINER_NAME }}
      ACCOUNT_KEY: ${{ secrets.ACCOUNT_KEY }}
      STATE_FILE: ${{ secrets.STATE_FILE }}
      CHECKPOINT_SESSION_NAME: GitHub Actions ${{ github.run_id }} $(date +'%Y-%m-%dT%H:%M:%SZ')
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
          
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 'latest'

      - name: Terraform init inventory
        run: |
          cd inventory
          ../scripts/tfinit.sh

      - name: Terraform apply inventory
        run: cd inventory; ../scripts/apply.sh
        
      - name: Publish policy
        run: |
          cd inventory; ../scripts/publish.sh
        
